#!/usr/bin/env dart
// Auto-generates lib/features/board/chat/cli_tools/auto_tools.dart from the
// YoLoIT CLI registry. Run with `dart run tool/generate_auto_tools.dart`.
// Run with `--check` to verify the committed file is up-to-date.
import 'dart:convert';
import 'dart:io';

final String _repoRoot = Directory.current.path;
final String _yoloitScript = '$_repoRoot/tools/yoloit';
final String _outputFile =
    '$_repoRoot/lib/features/board/chat/cli_tools/auto_tools.dart';
final String _manualToolsDir =
    '$_repoRoot/lib/features/board/chat/cli_tools';

void main(List<String> args) {
  final checkOnly = args.contains('--check');
  final registry = _loadRegistry();
  final existingCommands = _existingManualCommands();
  final missing =
      registry
          .where((c) => !existingCommands.contains(c['name'] as String))
          .toList();
  final generated = _generate(missing);

  if (checkOnly) {
    final current = File(_outputFile).readAsStringSync();
    if (current != generated) {
      stderr.writeln(
        '❌ $_outputFile is out of date.',
      );
      stderr.writeln(
        '   Run: dart run tool/generate_auto_tools.dart',
      );
      exit(1);
    }
    stdout.writeln('✅ $_outputFile is up to date.');
    return;
  }

  File(_outputFile).writeAsStringSync(generated);
  stdout.writeln('Generated $_outputFile (${missing.length} tools)');
}

List<Map<String, Object?>> _loadRegistry() {
  final result = Process.runSync(
    _yoloitScript,
    <String>['help', '--format', 'registry'],
    runInShell: false,
  );
  if (result.exitCode != 0) {
    stderr.writeln(result.stderr.toString());
    exit(1);
  }
  final decoded = jsonDecode(result.stdout.toString()) as List<dynamic>;
  return decoded.cast<Map<String, Object?>>();
}

Set<String> _existingManualCommands() {
  final commands = <String>{};
  final dir = Directory(_manualToolsDir);
  for (final entity in dir.listSync()) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    if (entity.path.endsWith('auto_tools.dart')) continue;
    final text = entity.readAsStringSync();
    for (final match in RegExp(r"command:\s*'([^']+)'").allMatches(text)) {
      commands.add(match.group(1)!);
    }
  }
  return commands;
}

String _generate(List<Map<String, Object?>> missing) {
  final lines = <String>[
    "import 'package:yoloit/features/board/chat/cli_tools/tool_helpers.dart';",
    "import 'package:yoloit/features/board/chat/yoloit_cli_tools.dart';",
    '',
    '// Auto-generated by tool/generate_auto_tools.dart',
    '// Do not edit manually; run `dart run tool/generate_auto_tools.dart`.',
    'final List<YoloitCliTool> autoTools = <YoloitCliTool>[',
  ];
  for (final cmd in missing) {
    lines.add(_buildToolCode(cmd));
  }
  lines.add('];');
  return '${lines.join('\n')}\n';
}

String _buildToolCode(Map<String, Object?> cmd) {
  final command = cmd['name']! as String;
  final group = (cmd['group'] as String?) ?? 'other';
  final description = (cmd['description'] as String?) ?? '';
  final params =
      ((cmd['params'] as List<dynamic>?) ?? <dynamic>[]).cast<List<dynamic>>();
  final aliases =
      ((cmd['aliases'] as List<dynamic>?) ?? <dynamic>[]).cast<String>();

  final paramCode = params.map(_buildParamCode).join(', ');
  final aliasCode =
      aliases.isEmpty
          ? ''
          : '\n    aliases: const [${aliases.map((a) => _dartString(a)).join(', ')}],';

  return '''  YoloitCliTool(
    command: ${_dartString(command)},
    description: ${_dartString(description)},$aliasCode
    group: ${_dartString(group)},
    params: <YoloitCliToolParam>[$paramCode],
  ),''';
}

String _buildParamCode(List<dynamic> param) {
  final name = param[0] as String;
  final description = param[1] as String;
  final required = param[2] as bool;
  final key = _paramKey(name);

  if (name == 'board' || name == '[board]' || key == 'board') {
    return 'boardParam()';
  }
  if (name == 'panel' || name == '[panel]' || key == 'panel') {
    return 'panelParam()';
  }

  final flag = name.startsWith('--') ? 'flag: ${_dartString(key)}' : null;
  final kind = _kindFor(name);
  final args = <String>[
    _dartString(key),
    _dartString(description),
    'required: $required',
  ];
  if (flag != null) args.add(flag);
  if (kind != 'YoloitCliToolParamKind.string') {
    args.add('kind: $kind');
  }
  return 'toolParam(${args.join(', ')})';
}

String _paramKey(String name) {
  var raw = name.trim();
  if (raw.startsWith('--')) {
    raw = raw.split(' ')[0].substring(2);
  }
  raw = raw.replaceAll('|', '_or_');
  raw = raw.replaceAll(RegExp(r'[^a-zA-Z0-9_]+'), '_');
  raw = raw.replaceAll(RegExp(r'_+'), '_');
  raw = raw.replaceAll(RegExp(r'^_+|_+$'), '');
  return raw.isEmpty ? 'arg' : raw.toLowerCase();
}

String _kindFor(String name) {
  final lower = name.toLowerCase();
  if (lower.contains('number') ||
      lower.contains('index') ||
      lower.contains('limit') ||
      lower.contains('duration') ||
      lower.contains('stroke_width')) {
    return 'YoloitCliToolParamKind.number';
  }
  if (lower == '--flutter' || lower == '--by') {
    return 'YoloitCliToolParamKind.boolean';
  }
  return 'YoloitCliToolParamKind.string';
}

String _dartString(String value) {
  final escaped = value
      .replaceAll('\\', '\\\\')
      .replaceAll("'", "\\'");
  return "'$escaped'";
}
