#!/usr/bin/env python3
"""Generate auto_tools.dart with YoloitCliTool entries missing from the LLM tool list.

Reads tools/yoloit registry, compares to existing tools in
lib/features/board/chat/yoloit_cli_tools.dart (and its imported cli_tools/*.dart files),
and emits a single auto_tools.dart file that is then spread into _tools.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
YOLOIT_SCRIPT = REPO_ROOT / 'tools' / 'yoloit'
TOOLS_DART = REPO_ROOT / 'lib' / 'features' / 'board' / 'chat' / 'yoloit_cli_tools.dart'
AUTO_TOOLS_DART = REPO_ROOT / 'lib' / 'features' / 'board' / 'chat' / 'cli_tools' / 'auto_tools.dart'


def _load_registry() -> list[dict]:
    result = subprocess.run(
        [str(YOLOIT_SCRIPT), 'help', '--format', 'registry'],
        capture_output=True, text=True, check=True,
    )
    return json.loads(result.stdout)


def _existing_commands(exclude_auto: bool = False) -> set[str]:
    text = TOOLS_DART.read_text(encoding='utf-8')
    # Resolve imported cli_tools/*.dart files relative to this file.
    imported = re.findall(r"import\s+'package:yoloit/features/board/chat/cli_tools/([^']+)'", text)
    commands = set(re.findall(r"command:\s*'([^']+)'", text))
    for rel in imported:
        if exclude_auto and rel == 'auto_tools.dart':
            continue
        path = REPO_ROOT / 'lib' / 'features' / 'board' / 'chat' / 'cli_tools' / rel
        if path.exists():
            commands.update(re.findall(r"command:\s*'([^']+)'", path.read_text(encoding='utf-8')))
    return commands


def _param_key(name: str) -> str:
    raw = name.strip().split()[0]
    if raw.startswith('--'):
        raw = raw[2:]
    raw = raw.replace('|', '_or_')
    key = re.sub(r'[^a-zA-Z0-9_]+', '_', raw)
    key = re.sub(r'_+', '_', key).strip('_').lower()
    return key or 'arg'


def _kind_for(name: str) -> str:
    lower = name.lower()
    if 'number' in lower or 'index' in lower or 'limit' in lower or 'duration' in lower or 'stroke_width' in lower:
        return 'YoloitCliToolParamKind.number'
    if lower in ('--flutter', '--by'):
        return 'YoloitCliToolParamKind.boolean'
    return 'YoloitCliToolParamKind.string'


def _build_param_code(param: list) -> str:
    name, desc, required = param
    key = _param_key(name)
    if name in ('board', '[board]') or key == 'board':
        return 'boardParam()'
    if name in ('panel', '[panel]') or key == 'panel':
        return 'panelParam()'
    flag = None
    if name.startswith('--'):
        flag = f"flag: '{key}'"
    kind = _kind_for(name)
    args = [f"'{key}'", f"'{desc}'", f"required: {str(required).lower()}"]
    if flag:
        args.append(flag)
    if kind != 'YoloitCliToolParamKind.string':
        args.append(f'kind: {kind}')
    return f"toolParam({', '.join(args)})"


def _build_tool_code(cmd: dict) -> str:
    command = cmd['name']
    group = cmd.get('group', 'other')
    description = cmd.get('description', f'yoloit {command}')
    params = cmd.get('params', [])
    param_code = ', '.join(_build_param_code(p) for p in params)
    return f'''  const YoloitCliTool(
    command: {command!r},
    description: {description!r},
    group: {group!r},
    params: <YoloitCliToolParam>[{param_code}],
  ),'''


def main() -> int:
    registry = _load_registry()
    existing = _existing_commands(exclude_auto=True)
    missing = [c for c in registry if c['name'] not in existing]

    lines = [
        "import 'package:yoloit/features/board/chat/cli_tools/tool_helpers.dart';",
        "import 'package:yoloit/features/board/chat/yoloit_cli_tools.dart';",
        '',
        '// Auto-generated by scripts/generate_missing_llm_tools.py',
        '// Covers CLI commands that do not yet have an explicit YoloitCliTool entry.',
        'final List<YoloitCliTool> autoTools = <YoloitCliTool>[',
    ]
    for cmd in missing:
        lines.append(_build_tool_code(cmd))
    lines.append('];')

    AUTO_TOOLS_DART.parent.mkdir(parents=True, exist_ok=True)
    AUTO_TOOLS_DART.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'Generated {AUTO_TOOLS_DART} ({len(missing)} tools)')

    # Add import and spread if not present.
    tools_text = TOOLS_DART.read_text(encoding='utf-8')
    import_line = "import 'package:yoloit/features/board/chat/cli_tools/auto_tools.dart';"
    if import_line not in tools_text:
        # Insert alphabetically after app_tools import.
        tools_text = tools_text.replace(
            "import 'package:yoloit/features/board/chat/cli_tools/app_tools.dart';\n",
            "import 'package:yoloit/features/board/chat/cli_tools/app_tools.dart';\n" + import_line + '\n',
        )
    if '...autoTools,' not in tools_text:
        tools_text = tools_text.replace(
            'final List<YoloitCliTool> _tools = <YoloitCliTool>[\n',
            'final List<YoloitCliTool> _tools = <YoloitCliTool>[\n  ...autoTools,\n',
        )
    TOOLS_DART.write_text(tools_text, encoding='utf-8')
    print(f'Updated {TOOLS_DART}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
